config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%=  f.text_field :details %>
  <%=  f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit your task</h1>

  <%= render "form", task: @task %>

  <p class="button"><%= link_to "Back to List", "/tasks" %></p>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>

  <ul>
    <% @tasks.each do |task| %>
        <li><%= link_to task.title, "/tasks/#{task.id}" %></li>
      <% end %>
  </ul>


  <p class="button"><%= link_to "Create a new task", "/tasks/new" %></p>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create a new Task</h1>

  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%=  f.text_field :details %>
    <%=  f.submit %>
  <% end %>


  <button><%= link_to "Back to List", "/tasks" %></button>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="flexbox">
    <h1><%= @task.title%></h1>
    <p class="button"><%= link_to "Edit this task", edit_task_path(@task) %></p>
  </div>

  <div class="details">
    <p><%= @task.details %></p>
  </div>

  <div class="completed">
    <p>This task is
      <%=
        if @task.completed
          "done! :)"
        else
          "not done"
        end
      %>
    </p>
  </div>

  <p class="button"><%= link_to "Delete",
    task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %></p>

  <p class="button"><%= link_to "Back to List", "/tasks" %></p>
</div>